version: "3"

services:
  db-postgres-ean:
    image: postgres:alpine
    ports:
      - "5435:5432"
    container_name: "db-postgres-rdobdc"
    restart: always
    volumes:
      - ./banco-de-dados-rdobdc:/var/lib/postgres/data
    environment:
      POSTGRES_USER: rdobdc
      POSTGRES_PASSWORD: rdobdc

volumes:
  banco-de-dados-rdobdc:
